GENERAL:
  name_exp: my_model
  checkpoints_dir: ./checkpoints
  model_dir: ./model
  log_dir: ./logs
  default_dtype: float64
  seed: 100

ARCHITECTURE:
  activation_fn: silu
  r_max: 6.
  r_max_lr: 12.0
  cutoff_fn: phys
  degrees: [1,2,3,4]
  dispersion_energy_bool: true
  dispersion_energy_scale: 1.2
  dispersion_energy_cutoff_lr_damping: 2.0
  electrostatic_energy_bool: true
  electrostatic_energy_scale: 4.0
  energy_activation_fn: silu
  energy_learn_atomic_type_scales: true
  energy_learn_atomic_type_shifts: true
  energy_regression_dim: 128
  input_convention: positions
  layer_normalization_1: true
  layer_normalization_2: true
  message_normalization: avg_num_neighbors
  num_features: 128
  num_heads: 4
  num_layers: 3
  num_radial_basis_fn: 32
  qk_non_linearity: identity
  radial_basis_fn: bernstein
  residual_mlp_1: true
  residual_mlp_2: false
  use_charge_embed: true
  use_spin_embed: true
  zbl_repulsion_bool: true
  neighborlist_format_lr: sparse
  compute_avg_num_neighbors: True

TRAINING:
  batch_size: 5
  valid_batch_size: 5
  weight_decay: 0.
  lr: 0.001
  optimizer: adam
  amsgrad: True
  scheduler: exponential_decay 
  lr_scheduler_gamma: 0.85
  energy_weight: 0.
  forces_weight: 1000.
  eval_interval: 1
  num_epochs: 5
  path_to_train_data: ./path/to/train/data
  valid_ratio: 0.1
  clip_grad: 10.0
  neighbors_lr_cutoff: 100.
  patience: 50


MISC:
  device: cpu
